AE-1192: Laatijan ohjeet
solita/etp-front pull request #569
Opened 2021-05-04 14:00 UTC by pasisem

AE-1192  Ohjesivun tietojen näyttäminen
AE-1193 Ohjeet header dropdown
AE-1194 Ohjesivujen navigaatio layout
AE-1276 Ohjesivun tietojen lisääminen ja muokkaaminen
AE-1277 Ohjesivun navigaation uudelleenjärjestäminen

2021-05-05 04:53 UTC, VesaLahd commented on src/App.svelte
>      Future.parallelObject(3, {
Tässä on mahdollista varmastikin nostaa tuota rinnakkaisuuden määrää neljään. Lähtee sitten pyynnöt yhtäaikaa eikä odoteta ensin yhden valmistumista.

2021-05-05 04:57 UTC, VesaLahd commented on src/components/Header/Header.svelte
> +  const hasNoParent = s => R.prop('parent-id', s).isNone();
`R.propSatisfies(Maybe.isNone, 'parent-id')`

2021-05-05 05:01 UTC, VesaLahd commented on src/components/Link/Link.svelte
> +<a {href} {target} class:disabled>
<!-- purgecss: disabled -->

2021-05-05 05:47 UTC, VesaLahd commented on src/components/ohje/creator.svelte
> +        const msg = $_(
Ihan tulevaisuuden kannalta nämä translaatio-accessit kannattaa kirjottaa siihen muotoon missä juuritasolla otetaan tuon storen sisältö muuttujaan ja sitten käytetään sitä sen läpi.

2021-05-05 07:26 UTC, VesaLahd commented on src/components/ohje/deleted.svelte
> +      <span class="material-icons text-primary"> delete </span>
Käytetään tuon tailwindin tarjoamaa font-icon classia mielummin nykyään.

2021-05-05 07:26 UTC, VesaLahd commented on src/components/ohje/deleted.svelte
> +    font-size: 54px;
En lähtisi laittelemaan pikseliarvoja fonttikoolle, mielummin em.

2021-05-05 09:52 UTC, VesaLahd commented on src/components/ohje/creator.svelte
> +    font-size: 54px;
px tässäkin

2021-05-05 09:55 UTC, VesaLahd commented on src/components/ohje/deleted.svelte
> +    font-size: 54px;
Tietty meillä taitaa tailwindistä löytyä classi text-6xl mikä lienee lähelle haluttua kokoa.

2021-05-05 09:58 UTC, VesaLahd commented on src/components/ohje/dragdrop.js
> +};
Tää on senverran geneerinen, että voisi siirtää jonnekin sille sopivaan paikkaan ja uudellenkirjoittaa esim file-uploadin d&dn käyttämään tätä samaa.

2021-05-05 10:00 UTC, VesaLahd commented on src/components/ohje/editor.svelte
> +        push(`/ohje/${params.id}`);
Tässä ei tuota pushia delayata resolvessa yhtään. Onko jokin syy miksi tuolla aikaisemmassa filussa niin tehtiin?

2021-05-05 10:00 UTC, VesaLahd commented on src/components/ohje/editor.svelte
> +        push('/ohje/deleted');
Kts yllä

2021-05-05 10:14 UTC, VesaLahd commented on src/components/ohje/nav-link.svelte
> +    class:childrenShown
Nää kannattaa myös kommentoida siihen purgecss-kommenttiin ettei purge vahingossa cullaa sääntöjä.

2021-05-05 10:19 UTC, VesaLahd commented on src/components/ohje/navigation.svelte
> +  $: id = R.last(R.split('/ohje/', $location));
id voisi kyllä tulla parametrinä sisään, kun eikös tätä käytetä pitkälti vain noista routen juurikontrollereista itsestään?

2021-05-05 10:22 UTC, VesaLahd commented on src/language/sv.json
> +    "ohjeet": "Laatijan ohjeet SV?",
Nyt kun meillä on tuo scripti mikä generoi tämän sv.jsonin, niin parempi kirjoittaa nämä vain fi.jsoniin ja ajaa sen scriptin jälkeenpäin. Ei tule mahdollisuuksia typoihin jne. Toki tuo tuskin oli käytössä tätä tehdessä, mutta jatkoa varten muistuttelen.

2021-05-05 10:25 UTC, VesaLahd requested changes
Muutama low hanging fruit korjattava homma, mutta muuten bueno 👍

2021-05-05 12:33 UTC, pasisem commented on src/components/ohje/deleted.svelte
> +      <span class="material-icons text-primary"> delete </span>
font-icon classilla nuo käyttäytyy hieman erillailla ja yleensä hieman hankaloittaa saamaan sellaista käyttäytymistä mitä haluan saada aikaan. Mutta kokeilen jos nopsaa onnistuu

2021-05-05 12:52 UTC, pasisem commented on src/components/ohje/editor.svelte
> +        push(`/ohje/${params.id}`);
Alunperin tein sen uuden sivun luonnissa että flashMessage ehtii näkyä koska silloin se ei vielä pushannut sille sivulle.

Poistin nyt sieltäkin. Ja poistin success flashMessaget näistä jotka pushataan toiselle sivulle.

2021-05-05 12:57 UTC, pasisem commented on src/components/ohje/navigation.svelte
> +  $: id = R.last(R.split('/ohje/', $location));
Joo, tämä on jäänyt siitä ajasta kun Navigation oli erikseen ja nuo muut routattiin. Päivitän parametriksi.

2021-05-06 06:23 UTC, pasisem commented on src/components/ohje/dragdrop.js
> +};
Siirsin utils kansioon dragdrop.js mutta en mene nyt file-uploadia muuttamaan

2021-05-11 07:50 UTC, VesaLahd approved these changes

2021-05-11 11:54 UTC, merged