Feature/ae 1361 energiatodistus state history
solita/etp-front pull request #653
Opened 2021-06-18 09:40 UTC by MattiNieminen

2021-06-18 09:42 UTC, MattiNieminen commented on src/components/Energiatodistus/muutoshistoria.svelte
> +  $: stateHistory = R.compose(
Tässä parsitaan aikaleimat, filtteröidään tulevaisuuden tapahtumat pois ja filtteröidään sellaiset tapahtumat, joille ei ole lokalisointia (mikä tarkoittaa myös sellaista tapahtumaa jota ei haluta edes näyttää.)

2021-06-18 09:43 UTC, MattiNieminen commented on src/components/Energiatodistus/muutoshistoria.svelte
> +
Täällä mäppäys eventin avaimen ja arvon perusteella oikeaan lokalisointiin.

2021-06-21 04:50 UTC, VesaLahd commented on src/components/Energiatodistus/muutoshistoria.svelte
> +    R.map(R.over(R.lensProp('modifytime'), dfns.parseJSON)),
Tää rivi vaikuttanee siltä, että sen kuuluisi olla apikutsun deserializessä.

2021-06-21 04:52 UTC, VesaLahd commented on src/components/Energiatodistus/muutoshistoria.svelte
> +    R.reverse,
Käyttäisin reversen sijaan jotain R.sort(R.descend(fn)) tyyppistä ratkaisua. Pelkkä taulukon reversointi kuitenkin luettavuuden kannalta on vähän kyseenalainen, kun koko rivistä sinällään puuttuu konteksti siitä miksi noin tehdään.

2021-06-21 04:53 UTC, VesaLahd commented on src/components/Energiatodistus/muutoshistoria.svelte
> +    R.map(R.prop('history'))
`R.chain(R.compose(Maybe.fromNull, R.path(['history', 'state-history'])))`

2021-06-21 04:54 UTC, VesaLahd commented on src/components/Energiatodistus/muutoshistoria.svelte
> +    R.map(event => R.assoc('localizationKey', stateLocalization(event), event)),
Tämä on mielestäni oma funkkarinsa.

2021-06-21 04:55 UTC, VesaLahd requested changes
Muutama juttu niin bueno

2021-06-21 11:14 UTC, MattiNieminen commented on src/components/Energiatodistus/muutoshistoria.svelte
> +    R.map(R.over(R.lensProp('modifytime'), dfns.parseJSON)),
Korjattu!

2021-06-21 11:17 UTC, MattiNieminen commented on src/components/Energiatodistus/muutoshistoria.svelte
> +    R.map(event => R.assoc('localizationKey', stateLocalization(event), event)),
Tehty oma funkkari.

2021-06-21 11:17 UTC, MattiNieminen commented on src/components/Energiatodistus/muutoshistoria.svelte
> +    R.reverse,
Done!

2021-06-21 11:20 UTC, MattiNieminen commented on src/components/Energiatodistus/muutoshistoria.svelte
> +    R.map(R.prop('history'))
:+1:

2021-06-21 11:39 UTC, VesaLahd approved these changes

2021-06-21 11:49 UTC, merged