AE-1814 ET search by postitoimipaikka
solita/etp-front pull request #950
Opened 2023-07-04 11:58 UTC by muep

2023-07-04 11:59 UTC, muep commented
Tähän tarvii tuon [etp-core/925](https://github.com/solita/etp-core/pull/925) jotta toimii

2023-07-05 11:07 UTC, muep commented
Tämä tarvitseekin nyt tuon [etp-core/#926](https://github.com/solita/etp-core/pull/926) kun ehkä se on parempi toteutustapa.

2023-07-06 05:20 UTC, Juholei requested changes

2023-07-06 05:20 UTC, Juholei commented on src/pages/energiatodistus/energiatodistus-haku/schema.js
> +const caseIntensitiveEqualsOperation = {
Typo

2023-07-06 05:20 UTC, Juholei commented on src/pages/energiatodistus/energiatodistus-haku/schema.js
> +const stringIsCaseInsentivelyEqual = key => ({
Typo

2023-07-06 06:09 UTC, muep commented on src/pages/energiatodistus/energiatodistus-haku/schema.js
> +const caseIntensitiveEqualsOperation = {
Korjasin

2023-07-06 06:09 UTC, muep commented on src/pages/energiatodistus/energiatodistus-haku/schema.js
> +const stringIsCaseInsentivelyEqual = key => ({
korjattu

2023-07-06 07:10 UTC, solita-antti-mottonen reviewed
Nimi operaattorin sijasta olisi minusta selkeämpi

2023-07-06 08:39 UTC, merged